### ISSUE TITLE
Plugin gets Shopify data multiple times per build

### ISSUE THREAD

**Issue by MWDelaney** [dleatherman/eleventy-plugin-shopify#9]
**Describe the bug**
This plugin is fetching shop data dozens of times per build

**To Reproduce**
I have an example repo! https://github.com/MWDelaney/ZeroPoint-Shopify

1. Clone the example repo
2. Create a `.env` file as described in this plugin's documentation
3. Run `yarn build` (or `npm run build`)
4. Note the wall of Shopify messages

**Expected behavior**
Shopify to get all the store data once, rather than dozens of times

**Additional context**
You mentioned on Twitter that you're aware of this bug, so hopefully this is enough information. If not, please let me know and I'll provide whatever you need! The plugin config is here: https://github.com/MWDelaney/ZeroPoint-Shopify/blob/master/src/config/plugins.js#L15-L34

**Comment by dleatherman** [comment]
Related: https://github.com/11ty/eleventy/milestone/37

**Comment by MWDelaney** [comment]
If I understand correctly this should resolve itself with Eleventy 1.0.1.

**Comment by dleatherman** [comment]
Yes, that's correct @MWDelaney. I also haven't yet looked into the settings for `node-fetch-cache` to make sure it's pulling from cache for each build instead of making new calls. It's definitely something I have in mind though.

**Comment by dleatherman** [comment]
Bumping dependency here to `^1.0.1-canary.3` to solve this issue.
